### ISSUE TITLE
Crash in CreateDynLightSourceHolder removeAll

### ISSUE THREAD

**Issue by MoePus** [leon-o/Create-Dynamic-Lights#6]
https://github.com/leon-o/Create-Dynamic-Lights/blob/cb96592ef4fad93addc61871175e85c8f3f6fec8/common/src/main/java/top/leonx/dynlight/lamb/CreateDynLightSourceHolder.java#L45

The getContraption method is nullable, causes crash

**Comment by DadamaldaDad** [comment]
I ran into this when a contraption was too large for a packet. Thanks for fixing this.
